# Generated by Django 6.0.5 on 2026-05-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['name'], 'verbose_name_plural': 'dish types'},
        ),
    ]
